fixed default and override member sig creation
nojaf/telplin pull request #12
Opened 2022-11-02 19:56 UTC by Martin521

2022-11-04 13:17 UTC, nojaf requested changes
Thank you! Good catch!

2022-11-04 13:17 UTC, nojaf commented on tests/Telplin.Core.Tests/TypeTests.fs
> +let ``Abstract member with default implementation`` () =
Could you please lowercase the test names?
See [docs](https://nojaf.com/telplin/docs/contributing.html#Pull-request-ground-rules).

I tried to do it myself but I can't seem to push it to your branch.

2022-11-06 20:35 UTC, Martin521 commented on tests/Telplin.Core.Tests/TypeTests.fs
> +let ``Abstract member with default implementation`` () =
Sure, I will.

2022-11-07 08:12 UTC, nojaf approved these changes
Many thanks!

2022-11-07 08:13 UTC, merged