Option 2 for correct extension member type names
nojaf/telplin pull request #14
Opened 2022-11-30 13:18 UTC by Martin521

2022-11-30 21:33 UTC, nojaf requested changes
Hi, thank you for your patience and both PRs. This is really good stuff and I very much appreciate your dedication here!

I have a couple of nitpicks but overall this is good stuff. Well done!

2022-11-30 21:33 UTC, nojaf commented on src/Telplin.UntypedTree/UntypedTree.fs
> +            match typeRepr with
I like that things are more scoped to the augmentation case.

2022-11-30 21:33 UTC, nojaf commented on src/Telplin.UntypedTree/UntypedTree.fs
> +    let typarMap =
I would write it a bit shorter:
```fsharp
    let typarMap =
        match typeRepr, typeParams with
        | SynTypeDefnRepr.ObjectModel (SynTypeDefnKind.Augmentation _, _, _), Some tps ->
            let originalTyparNames = resolver.GetTypeTyparNames typeInfo.Head.idRange.Proxy

            let extensionTyparIdents =
                tps.TyparDecls
                |> List.map (fun (SynTyparDecl (_, SynTypar (ident, _, _))) -> ident)

            if extensionTyparIdents.Length <> originalTyparNames.Length then
                failwith "unexpected difference in typar count"
            else
                List.zip originalTyparNames extensionTyparIdents |> Map
        | _ -> Map.empty
```

2022-11-30 21:33 UTC, nojaf commented on src/Telplin.UntypedTree/UntypedTree.fs
> +        else
Another nit you couldn't know about, but I use the [fsharp_experimental_keep_indent_in_branch](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_experimental_keep_indent_in_branch), but you can keep the indent of the else branch at the same level of the `else` keyword.
This is a good case for this, the if branch serves as an earlier return anyway.

2022-11-30 21:33 UTC, nojaf commented on src/Telplin.UntypedTree/UntypedTree.fs
> +            members |> List.map mapMember
Another nit, because this is so short I would write it as `List.map mapMember members` instead.

2022-11-30 21:33 UTC, nojaf commented on tests/Telplin.Core.Tests/BindingTests.fs
> +[<Test>]
I would move this test to `TypeTests` here. It is debatable, but given that the other test is already there.

2022-11-30 21:33 UTC, nojaf commented on tests/Telplin.Core.Tests/TypeTests.fs
> +    member TryFind: key: 'key -> 'value option
Could you add a test as well for the originally reported issue in https://github.com/nojaf/telplin/issues/8.
```fsharp
    assertSignature
        """
module Extensions

type List<'E> with

    member this.X = this.Head
"""
        """
module Extensions

type List<'E> with

    member X: 'E
"""
```

2022-12-01 13:57 UTC, Martin521 commented on src/Telplin.UntypedTree/UntypedTree.fs
> +        else
done

2022-12-01 14:00 UTC, Martin521 commented on tests/Telplin.Core.Tests/BindingTests.fs
> +[<Test>]
Done. I have also extended the test a bit to cover additional SynType cases

2022-12-01 14:00 UTC, Martin521 commented on tests/Telplin.Core.Tests/TypeTests.fs
> +    member TryFind: key: 'key -> 'value option
done

2022-12-01 14:01 UTC, Martin521 commented on src/Telplin.UntypedTree/UntypedTree.fs
> +            members |> List.map mapMember
done

2022-12-01 14:02 UTC, Martin521 commented on src/Telplin.UntypedTree/UntypedTree.fs
> +            match typeRepr with
I assume this is a positive comment and not a change request?

2022-12-02 18:04 UTC, nojaf approved these changes
Solid PR, many thanks for this!

2022-12-02 18:04 UTC, merged